### ISSUE TITLE
疑问

### ISSUE THREAD

**Issue by yisar** [Crossbell-Box/xLog#1362]
有一些疑问啊，就是

1. 现在所有的附件是存到 ipfs，然后自建的节点？也就是接口中的 web2Url
2. 接口数据呢？是存到数据库吗？还是区块链？
3. 区块链看起来是私有链？

综上，谢谢解答

**Comment by DIYgod** [comment]
1. The attachment is stored on IPFS and definitely needs to go through the server, unless all users are willing to install a local client and be required to be online 24 hours. For more details, you can query the working principle of IPFS.

2. Publishing content is directly done on the blockchain, while retrieving content is obtained from the database; otherwise, it would be too slow.

3. Considering user costs, currently we are running the chain. If we use the mainnet, users will need to purchase ETH for gas fees. Modifying an article each time would cost quite a bit of money, which I believe 99% of users wouldn't want. However, we are preparing to switch to L2 in order to better balance the conflicts between costs and decentralization.

**Comment by yisar** [comment]
L2 是啥？

我想问的重点是，如果现在的查询是走的数据库，那么区块链在这里的作用是什么呢？
另外，链上存什么东东呢？博客文章属于是大文本，存区块链上成本似乎超级高，【划重点，链上存了啥】

另外，如果走一些静态博客的思路，存到 ipfs 也不是不行，发布直接就是发 json

**Comment by DIYgod** [comment]
You can Google search blockchain layer 2.

As I said, the publication is directly published to the blockchain, which means that even if we delete or destroy the database, you can still access your data without permission.

The on-chain storage is an IPFS address.

**Comment by yisar** [comment]
好的伐，Layer2 俺知道的
还有一个思路，如果不走私链，其实随便找个测试链，自己请求水龙头，自己承担 gas，也是 ok 的

只是这样一来，不上公链，不发币，区块链在这里的作用可能就是它的一些特性（不可篡改，不可抹除）了
