### ISSUE TITLE
不太了解仪表盘里面的切换角色

### ISSUE THREAD

**Issue by whatqiu** [Crossbell-Box/xLog#237]
我是新手，第一次玩xlog,，=写了一篇文章发布后，看到域名可以更改我就更改了我的域名，然后就创建了一个新的角色，但是原先的角色没有我的文档，更改域名的角色有，请问这有问题吗？

是否可以删除角色或者合并呢？
![01](https://user-images.githubusercontent.com/14936273/226093350-27d2d2cc-2557-424d-be5d-ac0efec0ac8a.png)

**Comment by whatqiu** [comment]
Another problem is that you can follow  yourself and pay for it :sob:

**Comment by DIYgod** [comment]
Hello whatqiu, this is as expected. The article belongs to the current character rather than the entire address.

It is possible to delete characters, but it has not been added to the page yet. It is expected to be developed and completed next week.

And we do not restrict following oneself. Don't worry about gas fees, you will be reminded when they are running low so that you can continue to receive free CSB from the faucet.

This issue will be kept until character deletion is completed. 🥳

**Comment by whatqiu** [comment]
Thanks for your reply!🥳

**Comment by DIYgod** [comment]
The function of deleting character has already been implemented in [xFeed](https://xfeed.app/), so we will temporarily not implement it in xLog.
